import 'server-only';

/**
 * Identifiers are UUIDs generated by PostgreSQL (`gen_random_uuid()`).
 * Every query filters on a `uuid` column, so an identifier coming from a URL or
 * a cookie is validated first: an invalid value would make PostgreSQL raise
 * `22P02 invalid input syntax for type uuid`.
 */
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isUuid(value: string | null | undefined): value is string {
  return typeof value === 'string' && UUID_PATTERN.test(value);
}

/** True when PostgreSQL rejected a statement because of a unique constraint. */
export function isUniqueViolation(error: unknown): boolean {
  return (
    typeof error === 'object' &&
    error !== null &&
    'code' in error &&
    (error as { code?: string }).code === '23505'
  );
}